name: ${project.name}
main: name.richardson.james.bukkit.timedrestore.TimedRestorePlugin
description: ${project.description}
version: ${project.version}
depend: [WorldEdit, WorldGuard]
commands:
  tr:
    description: 'TimedRestore command'
    usage: '/tr'
